@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.rhms.userManagement.UserManager#loadAppointmentsForDoctor(Doctor)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.rhms.userManagement.UserManager",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_3499612 { 
   	label=rhms
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1951307539 { 
   	label=Database
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1904099134 { 
   	label=AppointmentDatabaseHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   AppointmentDatabaseHandler1676144448XXXloadAppointmentsForDoctor104431[
	label="+ loadAppointmentsForDoctor()"
	style=filled
	fillcolor=white
	tooltip="AppointmentDatabaseHandler

&#10;  Retrieves all appointments for a specific doctor&#10;  &#10;  @param doctorId The ID of the doctor&#10;  @return A list of appointments for the doctor&#10;  @throws SQLException If there is an error querying the database&#10; "
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_85584960 { 
   	label=userManagement
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_879193049 { 
   	label=UserManager
	labeljust=l
	fillcolor=white
	style=filled
   
   UserManager108603475XXXgetDoctorById104431[
	label="+ getDoctorById()"
	style=filled
	fillcolor=white
	tooltip="UserManager

null"
	fontcolor=darkgreen
];

UserManager108603475XXXgetPatientById104431[
	label="+ getPatientById()"
	style=filled
	fillcolor=white
	tooltip="UserManager

null"
	fontcolor=darkgreen
];

UserManager108603475XXXloadAppointmentsForDoctor2052357439[
	label="+ loadAppointmentsForDoctor()"
	style=filled
	fillcolor=white
	tooltip="UserManager

&#10;  Load appointments for a specific doctor from the database&#10;  @param doctor The doctor for whom to load appointments&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
AppointmentDatabaseHandler1676144448XXXloadAppointmentsForDoctor104431 -> UserManager108603475XXXgetDoctorById104431;
AppointmentDatabaseHandler1676144448XXXloadAppointmentsForDoctor104431 -> UserManager108603475XXXgetPatientById104431;
UserManager108603475XXXloadAppointmentsForDoctor2052357439 -> AppointmentDatabaseHandler1676144448XXXloadAppointmentsForDoctor104431;
    
}
@enduml