@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.rhms.userManagement.UserManager#registerPatient(String,String,String,String,String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.rhms.userManagement.UserManager",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_3499612 { 
   	label=rhms
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1177773926 { 
   	label=ui
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1040423513 { 
   	label=ManageUsersDashboardController
	labeljust=l
	fillcolor=white
	style=filled
   
   ManageUsersDashboardController1319010786XXXhandleAddUser1067311644[
	label="+ handleAddUser()"
	style=filled
	fillcolor=white
	tooltip="ManageUsersDashboardController

&#10;  Handle adding a new user&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1914743536 { 
   	label=MenuController
	labeljust=l
	fillcolor=white
	style=filled
   
   MenuController1844058119XXXshowMainMenu0[
	label="+ showMainMenu()"
	style=filled
	fillcolor=white
	tooltip="MenuController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_972420383 { 
   	label=RegistrationController
	labeljust=l
	fillcolor=white
	style=filled
   
   RegistrationController1319010786XXXhandleRegister1067311644[
	label="+ handleRegister()"
	style=filled
	fillcolor=white
	tooltip="RegistrationController

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_1331276484 { 
   	label=App
	labeljust=l
	fillcolor=white
	style=filled
   
   App660216151XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="App

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1951307539 { 
   	label=Database
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_42351050 { 
   	label=UserDatabaseHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   UserDatabaseHandler1676144448XXXaddUser2645995[
	label="+ addUser()"
	style=filled
	fillcolor=white
	tooltip="UserDatabaseHandler

null"
	fontcolor=darkgreen
];

UserDatabaseHandler1676144448XXXisEmailExists1808118735[
	label="+ isEmailExists()"
	style=filled
	fillcolor=white
	tooltip="UserDatabaseHandler

null"
	fontcolor=darkgreen
];

UserDatabaseHandler1676144448XXXisUsernameExists1808118735[
	label="+ isUsernameExists()"
	style=filled
	fillcolor=white
	tooltip="UserDatabaseHandler

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_85584960 { 
   	label=userManagement
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_879193049 { 
   	label=UserManager
	labeljust=l
	fillcolor=white
	style=filled
   
   UserManager108603475XXXregisterPatient878168891[
	label="+ registerPatient()"
	style=filled
	fillcolor=white
	tooltip="UserManager

&#10;  Registers a new patient in the system&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
App660216151XXXmain1859653459 -> UserManager108603475XXXregisterPatient878168891;
ManageUsersDashboardController1319010786XXXhandleAddUser1067311644 -> UserManager108603475XXXregisterPatient878168891;
MenuController1844058119XXXshowMainMenu0 -> UserManager108603475XXXregisterPatient878168891;
RegistrationController1319010786XXXhandleRegister1067311644 -> UserManager108603475XXXregisterPatient878168891;
UserManager108603475XXXregisterPatient878168891 -> UserDatabaseHandler1676144448XXXaddUser2645995;
UserManager108603475XXXregisterPatient878168891 -> UserDatabaseHandler1676144448XXXisEmailExists1808118735;
UserManager108603475XXXregisterPatient878168891 -> UserDatabaseHandler1676144448XXXisUsernameExists1808118735;
    
}
@enduml