@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.rhms.userManagement.UserManager#loadAppointmentsForPatient(Patient)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.rhms.userManagement.UserManager",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_3499612 { 
   	label=rhms
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1177773926 { 
   	label=ui
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1471229367 { 
   	label=PatientDashboardController
	labeljust=l
	fillcolor=white
	style=filled
   
   PatientDashboardController1319010786XXXinitializeDashboard0[
	label="+ initializeDashboard()"
	style=filled
	fillcolor=white
	tooltip="PatientDashboardController

&#10;  Initializes the dashboard with user-specific data&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_355486142 { 
   	label=LoginViewController
	labeljust=l
	fillcolor=white
	style=filled
   
   LoginViewController1319010786XXXinitialize0[
	label="+ initialize()"
	style=filled
	fillcolor=white
	tooltip="LoginViewController

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_1951307539 { 
   	label=Database
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1904099134 { 
   	label=AppointmentDatabaseHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   AppointmentDatabaseHandler1676144448XXXloadAppointmentsForPatient104431[
	label="+ loadAppointmentsForPatient()"
	style=filled
	fillcolor=white
	tooltip="AppointmentDatabaseHandler

&#10;  Retrieves all appointments for a specific patient&#10;  &#10;  @param patientId The ID of the patient&#10;  @return A list of appointments for the patient&#10;  @throws SQLException If there is an error querying the database&#10; "
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_85584960 { 
   	label=userManagement
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_879193049 { 
   	label=UserManager
	labeljust=l
	fillcolor=white
	style=filled
   
   UserManager108603475XXXgetDoctorById104431[
	label="+ getDoctorById()"
	style=filled
	fillcolor=white
	tooltip="UserManager

null"
	fontcolor=darkgreen
];

UserManager108603475XXXgetPatientById104431[
	label="+ getPatientById()"
	style=filled
	fillcolor=white
	tooltip="UserManager

null"
	fontcolor=darkgreen
];

UserManager108603475XXXloadAppointmentsForPatient873235173[
	label="+ loadAppointmentsForPatient()"
	style=filled
	fillcolor=white
	tooltip="UserManager

&#10;  Load appointments for a specific patient from the database&#10;  @param patient The patient for whom to load appointments&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
AppointmentDatabaseHandler1676144448XXXloadAppointmentsForPatient104431 -> UserManager108603475XXXgetDoctorById104431;
AppointmentDatabaseHandler1676144448XXXloadAppointmentsForPatient104431 -> UserManager108603475XXXgetPatientById104431;
LoginViewController1319010786XXXinitialize0 -> PatientDashboardController1319010786XXXinitializeDashboard0;
PatientDashboardController1319010786XXXinitializeDashboard0 -> UserManager108603475XXXloadAppointmentsForPatient873235173;
UserManager108603475XXXloadAppointmentsForPatient873235173 -> AppointmentDatabaseHandler1676144448XXXloadAppointmentsForPatient104431;
    
}
@enduml